In [1]:
from data_model import WineData, WHITE_WINE_PATH
from network import run
from torch.utils.data import Dataset, DataLoader


In [2]:
model = run()

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 5])
number of classs is 7
Epoch[50] Loss:[1.11]
EVALUATOR: Training Results - Epoch: 50  Avg accuracy: 0.53 Avg loss: 1.1034
Epoch[100] Loss:[0.97]
EVALUATOR: Training Results - Epoch: 100  Avg accuracy: 0.54 Avg loss: 1.0911
Epoch[150] Loss:[1.05]
EVALUATOR: Training Results - Epoch: 150  Avg accuracy: 0.54 Avg loss: 1.0844
Epoch[200] Loss:[1.25]
EVALUATOR: Training Results - Epoch: 200  Avg accuracy: 0.53 Avg loss: 1.0808


In [3]:
import shap

In [4]:
data = WineData.read_data(WHITE_WINE_PATH)

train_data, test_data = WineData.train_test_splitter(data)

wd = WineData(train_data)
wd_test = WineData(test_data)

# classes = wd.number_of_classes
# model = NeuralNet(wd.x_data.shape[1], 200, classes)
train_loader = DataLoader(dataset=wd, batch_size=124, shuffle=True, num_workers=0)
test_loader = DataLoader(
    dataset=wd_test, batch_size=124, shuffle=True, num_workers=0
)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 5])


In [5]:
batch = next(iter(train_loader))
inputs, _ = batch

background = inputs[:80]
test_inputs = inputs[80:]

In [6]:
e = shap.DeepExplainer(model, background)

In [ ]:
e.shap_values(background)

In [12]:
model(background[0])

tensor(2.0945, grad_fn=<MaxBackward1>)